source 'https://rubygems.org'

# gem 'fast-stemmer'
# gem 'hitimes'
# gem 'redcarpet'
# gem 'snappy'
# gem 'pg'
# gem 'mysql2'
# gem 'puma', '3.8.2', :platforms => :ruby
# gem 'kgio', :platforms => :ruby
# gem 'raindrops', :platforms => :ruby
# gem 'unicorn', :platforms => :ruby
#gem 'curses', :platforms => :ruby
gem 'nokogiri', '1.7.1'
gem 'RedCloth', '4.3.1'
gem 'rinku'
gem 'sqlite3'
gem 'mysql2', '0.3.18'
gem 'unicorn', '4.9.0'
gem 'bcrypt', '3.1.10'
